version: "3"
services:
  app:
    build: ./
    restart: always
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_API_KEY=$GOOGLE_AUTH_KEYS
      - GOOGLE_API_REFRESH_INTERVAL=$GOOGLE_API_REFRESH_INTERVAL
      - HOST=$HOST
      - PORT=$PORT
      - MONGO_HOST=$MONGO_HOST
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DBNAME=$MONGO_DBNAME
      - REDIS_PORT=$REDIS_PORT
      - REDIS_HOST=$REDIS_HOST
      - YT_SEARCH_QUERY=$YT_SEARCH_QUERY
    command:
      sh -c 'npm i && npm start'
    links:
      - mongo
      - redis

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: fampay
    ports:
      - "27017:27017"

  redis:
    container_name: redis
    image: redis
    expose:
      - 6379